### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by loneicewolf** [cfuendev/snippies#3]
Hello there!
Just wanted to say thank you for sharing this repo; this in particular is very useful:
https://github.com/cfuendev/snippies/blob/main/snippets/color-parse.js

Have a great week! And happy (early) Christmas `^_^`

Wishes from Sweden!

_this can be closed as it's not _really_ an 'issue'_

**Comment by cfuendev** [comment]
Thank you! ❤️ This took an awful lot of research in the MDN docs, a bunch of LLM (ChatGPT) questions, then hours of trial and error. I honestly didn't expect someone to actually stumble upon this repo and find anything inside it useful, so I'm flattered to know it's being implemented in other projects! Makes me realize it IS important to document my snippets as well as I can.

Do show what project you're using `color-parse.js` for, if you don't mind. I'm interested now!

Also, feel free to PR if there's anything useful you want to include into `color-parse.js`, I'll review it! ✨

Happy new years and merry Christmas to you too!

**Comment by loneicewolf** [comment]
Hello again! Yes;

> Do show what project you're using `color-parse.js` for, if you don't mind. I'm interested now!

I do not use it for any specific project - but it was a really neat list of colors, instead of needing to google "color xyz copy paste" or "xyz color code" etc etc; and so on - I just found it useful ^_^ and I also will begin to code in js so it helps a lot as well; 

### **Although if I ever use it in a project, I will mention you!** 


> Also, feel free to PR if there's anything useful you want to include into `color-parse.js`, I'll review it! ✨

Awesome, right now I don't really find anything to PR, and I can't (*yet) code in js, so I always tell myself to learn myself the language, first before PR'ing but to me it looks just good right now! :)

Thanks and sorry for a bit late reply;

**Comment by cfuendev** [comment]
Understood. Thanks for the kind words! ❤️ And I'm very glad this was useful to you.
Good luck getting started with JS.. You might need it 😅 JS can be [messy and confusing](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) from time to time, but it's fun once you get the hang of it. It's the language that I spend most time writing, and it's not perfect, yet I can't help but love writing it.

Really looking forward more ppl finding stuff in this repo useful just like you. Your comments gave me some hope! ✨

**Comment by loneicewolf** [comment]
Oh okay yes! `:D` 
> Really looking forward more ppl finding stuff in this repo useful just like you. Your comments gave me some hope! ✨
Yeah; they will ^_^ I'm sure, and good luck! also Happy I could 'help' by just Making a 
"issue" explaining it was a good repo `:P` but yes I mean it 

Have a nice day!
